import { FormEvent, useEffect, useState } from "react";
import styles from "../styles/Home.module.css";

const people=[["richard","Richard Darling"],["anastasia","Anastasia Ferrari"],["jean","Jean-Claude Bērziņš"],["kevin","Kevin von Whatever"],["svetlana","Svetlana de Monte Carlo"]];
const initials:any={richard:"RD",anastasia:"AF",jean:"JB",kevin:"KV",svetlana:"SM"};

export default function Home(){
 const [role,setRole]=useState("richard"); const [dash,setDash]=useState<any>(null); const [message,setMessage]=useState("System ready");
 const load=async()=>{const r=await fetch(`/api?action=dashboard&actor=${encodeURIComponent(role)}`);setDash(await r.json());}; useEffect(()=>{void load();},[role]);
 async function api(payload:any){const r=await fetch("/api",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...payload,actor:role})});const j=await r.json();setMessage(j.ok?`✓ ${j.reference||payload.reference||payload.action}: ${j.status||"completed"}`:`✕ ${j.error||"Request failed"}`);await load();return j;}
 const manager=role==="svetlana", salesperson=["richard","anastasia","jean"].includes(role), expenseReporter=role==="kevin";
 return <main className={styles.shell}>
  <aside className={styles.sidebar}><div className={styles.brand}><div className={styles.logo}>F</div><div>FRIENDS INCLUDED<small>FINANCE</small></div></div><nav><a href="#dashboard">⌂ <span>Dashboard</span></a><a href="#sale">↗ <span>New Sale</span></a><a href="#expense">▣ <span>New Expense</span></a><a href="#approvals">✓ <span>Approvals</span></a><a href="#records">▤ <span>Records</span></a><a href="#links">◈ <span>Data & Links</span></a></nav><div className={styles.botbox}><b>Finance Bot</b><p>Sales, expenses and approval notifications connected through Telegram.</p><a href={process.env.NEXT_PUBLIC_TELEGRAM_BOT_URL||"#"}>Open Telegram ↗</a></div><div className={styles.owner}><span>DS</span><div><b>Denis Shuvayev</b><small>Project owner</small></div></div></aside>
  <div className={styles.page}>
   <header className={styles.hero}><div><p className={styles.eyebrow}>Day 4 Homework · Finance Operations</p><h1>Friends Included Finance</h1><p>Sales, expenses, approvals and project performance — in one place.</p></div><div className={styles.live}>● All systems online</div></header>
   <section className={styles.topbar}><div><span className={styles.avatar}>{initials[role]}</span><select value={role} onChange={e=>setRole(e.target.value)}>{people.map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></div><small>Demo role · permissions enforced server-side</small></section>
   <section id="dashboard" className={styles.kpis}>{dash?.projectA?<><Kpi icon="◆" label="Company Result" value={dash.company.result}/><Kpi icon="A" label="Project A Result" value={dash.projectA.result}/><Kpi icon="B" label="Project B Result" value={dash.projectB.result}/><Kpi icon="◫" label="Overhead" value={dash.company.overhead}/><Kpi icon="◷" label="Awaiting" value={dash.company.awaiting}/></>:<p>Loading financial data…</p>}</section>
   {dash?.projectA&&<div className={styles.grid}><section className={styles.panel}><div className={styles.sectionTitle}><div><p className={styles.eyebrow}>PERFORMANCE</p><h2>Project Results</h2></div><span className={styles.pill}>Live</span></div><ProjectBars dash={dash}/></section><section className={styles.panel}><p className={styles.eyebrow}>TEAM</p><h2>Commission Earned</h2><div className={styles.commission}><Commission name="Richard" value={dash.commissions.richard}/><Commission name="Anastasia" value={dash.commissions.anastasia}/><Commission name="Jean-Claude" value={dash.commissions.jean}/></div></section></div>}
   <div className={styles.grid}>
    <section id="sale" className={styles.panel}><p className={styles.eyebrow}>TRANSACTION</p><h2>Log New Sale</h2>{!salesperson&&<Notice>Switch to a salesperson role to submit.</Notice>}<form onSubmit={async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=e.currentTarget,j=await api({action:"sale",...Object.fromEntries(new FormData(form).entries())});if(j.ok)form.reset();}}>{["reference","customer","description","amount","proposed_richard","proposed_anastasia","proposed_jean"].map(n=><input key={n} name={n} required placeholder={n.split("_").join(" ")} type={n.includes("amount")||n.includes("proposed")?"number":"text"} step="0.01"/>)}<select name="project"><option>A</option><option>B</option></select><button disabled={!salesperson}>Submit sale →</button></form></section>
    <section id="expense" className={styles.panel}><p className={styles.eyebrow}>TRANSACTION</p><h2>Log New Expense</h2>{!expenseReporter&&<Notice>Switch to Kevin von Whatever to submit.</Notice>}<form onSubmit={async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=e.currentTarget,j=await api({action:"expense",...Object.fromEntries(new FormData(form).entries())});if(j.ok)form.reset();}}><input required name="reference" placeholder="reference"/><input required name="description" placeholder="description"/><select name="category"><option>Materials</option><option>Travel</option><option>Other</option></select><input required name="amount" type="number" min="0.01" step="0.01" placeholder="amount"/><select name="proposed_allocation"><option>A</option><option>B</option><option>Company overhead</option></select><button disabled={!expenseReporter}>Submit expense →</button></form></section>
   </div>
   {manager&&dash&&<section id="approvals" className={styles.panel}><div className={styles.sectionTitle}><div><p className={styles.eyebrow}>MANAGER CONTROL</p><h2>Approvals & Allocation</h2></div><span className={styles.pill}>{(dash.pendingSales?.length||0)+(dash.awaitingExpenses?.length||0)} open</span></div><h3>Pending sales</h3>{dash.pendingSales?.map((s:any)=><SaleApproval key={s.reference}s={s}api={api}/>)}<h3>Awaiting expense allocation</h3>{dash.awaitingExpenses?.map((e:any)=><ExpenseApproval key={e.reference}e={e}api={api}/>)}</section>}
   <section id="records" className={styles.panel}><div className={styles.sectionTitle}><div><p className={styles.eyebrow}>LEDGER</p><h2>{manager?"All Records":"My Submissions"}</h2></div><span className={styles.pill}>{(dash?.visibleSales?.length||0)+(dash?.visibleExpenses?.length||0)} records</span></div><div className={styles.recordGrid}>{dash?.visibleSales?.map((x:any)=><Record key={x.reference}x={x}kind="sale"manager={manager}api={api}/>)}{dash?.visibleExpenses?.map((x:any)=><Record key={x.reference}x={x}kind="expense"manager={manager}api={api}/>)}</div></section>
   <section className={styles.panel}><div className={styles.sectionTitle}><div><p className={styles.eyebrow}>REVIEW GUIDE</p><h2>Safe Testing Instructions</h2></div><span className={styles.pill}>Fictional homework data only</span></div><div className={styles.instructions}><p><b>1 · Start</b><span>Open the Telegram bot and send <code>/start</code>.</span></p><p><b>2 · Link</b><span>Switch this website to Svetlana (manager) and link the reviewer's Telegram user ID and chat ID to the fictional employee being tested.</span></p><p><b>3 · Submit</b><span>Use clearly labelled test references. Sale: <code>/sale | REF | Customer | A | Description | 100 | 50 | 30 | 20</code><br/>Expense: <code>/expense | REF | Description | Materials | 10 | A</code></span></p><p><b>4 · Review</b><span>Approve or correct only the labelled reviewer test records in the manager view. Pending sales stay out of profit; awaiting expenses reduce company result.</span></p><p><b>5 · Unlink</b><span>After testing, use “Remove matching test binding” below. It removes only the selected employee binding when the entered Telegram user ID still matches, so another user's newer binding cannot be removed accidentally.</span></p></div></section>
   {manager&&<section className={styles.panel}><p className={styles.eyebrow}>INTEGRATION</p><h2>Telegram Linking</h2><form className={styles.horizontal} onSubmit={async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();await api({action:"linkTelegram",...Object.fromEntries(new FormData(e.currentTarget).entries())});}}><select name="employee_code">{people.map(([v,n])=><option key={v}value={v}>{n}</option>)}</select><input required name="telegram_user_id" placeholder="Telegram user ID"/><input required name="telegram_chat_id" placeholder="Telegram chat ID"/><button>Save link</button></form><h3>Remove reviewer test binding</h3><form className={styles.horizontal} onSubmit={async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=e.currentTarget,j=await api({action:"unlinkTelegram",...Object.fromEntries(new FormData(form).entries())});if(j.ok)form.reset();}}><select name="employee_code">{people.map(([v,n])=><option key={v}value={v}>{n}</option>)}</select><input required name="telegram_user_id" placeholder="Reviewer Telegram user ID"/><div></div><button>Remove matching test binding</button></form><p className={styles.notice}>Safety check: unlink succeeds only if the selected employee is still linked to that exact Telegram user ID. Historical transaction notification chats are not changed.</p></section>}
   <section id="links" className={styles.integrations}><a href={process.env.NEXT_PUBLIC_TELEGRAM_BOT_URL||"#"}><b>Telegram Bot</b><span>Connected ↗</span></a><a href={process.env.NEXT_PUBLIC_GOOGLE_SHEET_URL||"#"}><b>Google Sheets</b><span>Synced ↗</span></a><a href={process.env.NEXT_PUBLIC_GITHUB_URL||"https://github.com/QAZAQ7/dslastwork"}><b>GitHub</b><span>Source ↗</span></a><div><b>Supabase + Vercel</b><span>Production ready</span></div></section>
   <footer><span>{message}</span><span>Built by Denis Shuvayev · 2026</span></footer>
  </div>
 </main>
}
function Kpi({icon,label,value}:{icon:string,label:string,value:number}){return <div className={styles.kpi}><span className={styles.kpiIcon}>{icon}</span><div><small>{label}</small><strong>€{Number(value||0).toLocaleString("en-US",{minimumFractionDigits:2})}</strong></div></div>}
function ProjectBars({dash}:{dash:any}){const vals=[["Project A",dash.projectA.result],["Project B",dash.projectB.result],["Company",dash.company.result]];const max=Math.max(...vals.map(x=>Number(x[1])));return <div className={styles.bars}>{vals.map(([n,v]:any)=><div key={n}><span>{n}<b>€{Number(v).toLocaleString()}</b></span><i><em style={{width:`${Math.max(4,Number(v)/max*100)}%`}}/></i></div>)}</div>}
function Commission({name,value}:{name:string,value:number}){return <div><span><i/> {name}</span><b>€{Number(value||0).toFixed(2)}</b></div>}
function Notice({children}:{children:any}){return <p className={styles.notice}>{children}</p>}
function Record({x,kind,manager,api}:{x:any,kind:string,manager:boolean,api:(p:any)=>Promise<any>}){return <article className={styles.record}><div><b>{x.reference}</b><span className={x.status.includes("Approved")||x.status.includes("Allocated")?styles.good:styles.wait}>{x.status}</span></div><strong>€{Number(x.amount).toFixed(2)}</strong><small>{kind==="sale"?`Project ${x.project}`:x.final_allocation||x.proposed_allocation}</small><small>Sheets: {x.sheet_sync_status} · Telegram: {x.notification_status==="no_recipient"?"not linked":x.notification_status}</small>{manager&&x.sheet_sync_status==="failed"&&<button onClick={()=>api({action:"retrySync",kind,reference:x.reference})}>Retry sync</button>}{manager&&x.notification_status==="failed"&&<button onClick={()=>api({action:"retryNotification",kind,reference:x.reference})}>Retry notification</button>}</article>}
function SaleApproval({s,api}:{s:any,api:(p:any)=>Promise<any>}){const[r,setR]=useState(String(s.proposed_richard)),[a,setA]=useState(String(s.proposed_anastasia)),[j,setJ]=useState(String(s.proposed_jean));return <div className={styles.approval}><div><b>{s.reference}</b><small>€{Number(s.amount).toFixed(2)} · Project {s.project} · proposed {s.proposed_richard}/{s.proposed_anastasia}/{s.proposed_jean}</small></div><div><input value={r}onChange={e=>setR(e.target.value)}/><input value={a}onChange={e=>setA(e.target.value)}/><input value={j}onChange={e=>setJ(e.target.value)}/><button onClick={()=>api({action:"approveSale",reference:s.reference,approved_richard:Number(r),approved_anastasia:Number(a),approved_jean:Number(j)})}>Approve</button></div></div>}
function ExpenseApproval({e,api}:{e:any,api:(p:any)=>Promise<any>}){const[v,setV]=useState(e.proposed_allocation);return <div className={styles.approval}><div><b>{e.reference}</b><small>€{Number(e.amount).toFixed(2)} · proposed {e.proposed_allocation}</small></div><div><select value={v}onChange={x=>setV(x.target.value)}><option>A</option><option>B</option><option>Company overhead</option></select><button onClick={()=>api({action:"approveExpense",reference:e.reference,final_allocation:v})}>Confirm</button></div></div>}