import { FormEvent, useEffect, useState } from "react";
import styles from "../styles/Home.module.css";

const people=[
  ["richard","Richard Darling"],["anastasia","Anastasia Ferrari"],["jean","Jean-Claude Bērziņš"],["kevin","Kevin von Whatever"],["svetlana","Svetlana de Monte Carlo"]
];

export default function Home(){
  const [role,setRole]=useState("richard"); const [dash,setDash]=useState<any>(null); const [message,setMessage]=useState("Ready.");
  const load=async()=>{const r=await fetch(`/api?action=dashboard&actor=${encodeURIComponent(role)}`); const j=await r.json(); setDash(j);};
  useEffect(()=>{void load();},[role]);
  async function api(payload:any){const r=await fetch("/api",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...payload,actor:role})}); const j=await r.json(); setMessage(JSON.stringify(j,null,2)); await load(); return j;}
  const manager=role==="svetlana";
  return <main className={styles.main}>
    <header className={styles.hero}><p className={styles.eyebrow}>Day 4 Homework</p><h1>Friends Included — Finance System</h1><p>Denis Shuvayev</p></header>
    <section className={styles.card}><label><b>Demonstration role</b></label><select value={role} onChange={e=>setRole(e.target.value)}>{people.map(([v,n])=><option key={v} value={v}>{n}</option>)}</select><small>Server-side permissions are enforced in the API.</small></section>
    <div className={styles.grid}>
      <section className={styles.card}><h2>Submit sale</h2><form onSubmit={async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);await api({action:"sale",...Object.fromEntries(f.entries())});e.currentTarget.reset();}}>{["reference","customer","description","amount","proposed_richard","proposed_anastasia","proposed_jean"].map(n=><input key={n} name={n} placeholder={n.replaceAll("_"," ")} type={n.includes("amount")||n.includes("proposed")?"number":"text"} step="0.01"/>)}<select name="project"><option>A</option><option>B</option></select><button>Submit sale</button></form></section>
      <section className={styles.card}><h2>Submit expense</h2><form onSubmit={async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);await api({action:"expense",...Object.fromEntries(f.entries())});e.currentTarget.reset();}}><input name="reference" placeholder="reference"/><input name="description" placeholder="description"/><select name="category"><option>Materials</option><option>Travel</option><option>Other</option></select><input name="amount" type="number" step="0.01" placeholder="amount"/><select name="proposed_allocation"><option>A</option><option>B</option><option>Company overhead</option></select><button>Submit expense</button></form></section>
    </div>
    <section className={styles.card}><h2>Financial dashboard</h2>{dash?.projectA?<><div className={styles.grid}><ProjectPanel title="Project A — Respectable Relatives" p={dash.projectA}/><ProjectPanel title="Project B — Drunk University Friends" p={dash.projectB}/></div><div className={styles.metrics}><Metric t="Company overhead" v={dash.company.overhead}/><Metric t="Expenses awaiting allocation" v={dash.company.awaiting}/><Metric t="Total company result" v={dash.company.result}/><div><b>Commission earned</b><p>Richard €{Number(dash.commissions.richard).toFixed(2)}<br/>Anastasia €{Number(dash.commissions.anastasia).toFixed(2)}<br/>Jean-Claude €{Number(dash.commissions.jean).toFixed(2)}</p></div></div></>:<p>Connect Supabase environment variables.</p>}</section>
    {manager&&dash&&<section className={styles.card}><h2>Manager approvals</h2><h3>Pending sales</h3>{dash.pendingSales?.map((s:any)=><SaleApproval key={s.reference} s={s} api={api}/>)}<h3>Awaiting expense allocations</h3>{dash.awaitingExpenses?.map((e:any)=><ExpenseApproval key={e.reference} e={e} api={api}/>)}</section>}
    <section className={styles.card}><h2>{manager?"All records":"My submissions"}</h2><h3>Sales</h3>{dash?.visibleSales?.map((x:any)=><Record key={x.reference} x={x} kind="sale" manager={manager} api={api}/>)}<h3>Expenses</h3>{dash?.visibleExpenses?.map((x:any)=><Record key={x.reference} x={x} kind="expense" manager={manager} api={api}/>)}</section>
    {manager&&<section className={styles.card}><h2>Telegram linking</h2><form onSubmit={async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);await api({action:"linkTelegram",...Object.fromEntries(f.entries())});}}><select name="employee_code">{people.map(([v,n])=><option key={v} value={v}>{n}</option>)}</select><input name="telegram_user_id" placeholder="Telegram user ID"/><input name="telegram_chat_id" placeholder="Telegram chat ID"/><button>Save link</button></form></section>}
    <section className={styles.card}><h2>Submission links</h2><p><a href={process.env.NEXT_PUBLIC_TELEGRAM_BOT_URL||"#"}>Telegram bot</a> · <a href={process.env.NEXT_PUBLIC_GOOGLE_SHEET_URL||"#"}>Google Sheets</a> · <a href={process.env.NEXT_PUBLIC_GITHUB_URL||"#"}>GitHub</a></p><p>Select a role. Salespeople submit sales, Kevin submits expenses, and Svetlana approves/corrects decisions.</p></section>
    <section className={styles.card}><h2>System response</h2><pre>{message}</pre></section>
  </main>
}
function Metric({t,v}:{t:string,v:number}){return <div><b>{t}</b><div className={styles.big}>€{Number(v||0).toFixed(2)}</div></div>}
function ProjectPanel({title,p}:{title:string,p:any}){return <div className={styles.record}><b>{title}</b><p>Approved income: €{Number(p.income||0).toFixed(2)}<br/>Commission expense: €{Number(p.commission||0).toFixed(2)}<br/>Allocated expenses: €{Number(p.allocated||0).toFixed(2)}<br/><strong>Result: €{Number(p.result||0).toFixed(2)}</strong></p></div>}
function Record({x,kind,manager,api}:{x:any,kind:string,manager:boolean,api:(p:any)=>Promise<any>}){return <div className={styles.record}><b>{x.reference}</b> — €{Number(x.amount).toFixed(2)} — {x.status}<small>Sheet: {x.sheet_sync_status} · Notification: {x.notification_status==="no_recipient"?"No Telegram recipient linked":x.notification_status}</small>{manager&&x.sheet_sync_status==="failed"&&<button onClick={()=>api({action:"retrySync",kind,reference:x.reference})}>Retry Sheets sync</button>}{manager&&x.notification_status==="failed"&&<button onClick={()=>api({action:"retryNotification",kind,reference:x.reference})}>Retry Telegram notification</button>}</div>}
function SaleApproval({s,api}:{s:any,api:(p:any)=>Promise<any>}){const[r,setR]=useState(String(s.proposed_richard));const[a,setA]=useState(String(s.proposed_anastasia));const[j,setJ]=useState(String(s.proposed_jean));return <div className={styles.record}><b>{s.reference}</b> — €{Number(s.amount).toFixed(2)} — Project {s.project}<small>Proposed {s.proposed_richard}/{s.proposed_anastasia}/{s.proposed_jean}</small><div className={styles.inline}><input value={r} onChange={e=>setR(e.target.value)}/><input value={a} onChange={e=>setA(e.target.value)}/><input value={j} onChange={e=>setJ(e.target.value)}/><button onClick={()=>api({action:"approveSale",reference:s.reference,approved_richard:Number(r),approved_anastasia:Number(a),approved_jean:Number(j)})}>Approve</button></div></div>}
function ExpenseApproval({e,api}:{e:any,api:(p:any)=>Promise<any>}){const[v,setV]=useState(e.proposed_allocation);return <div className={styles.record}><b>{e.reference}</b> — €{Number(e.amount).toFixed(2)}<small>Proposed: {e.proposed_allocation}</small><div className={styles.inline}><select value={v} onChange={x=>setV(x.target.value)}><option>A</option><option>B</option><option>Company overhead</option></select><button onClick={()=>api({action:"approveExpense",reference:e.reference,final_allocation:v})}>Confirm</button></div></div>}
